title: "Windows 11 Notes & Shortcuts"
description: "A site using Just the Docs theme"
remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme  # Enables remote theme support

nav_enabled: true
